kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-demo-app-config-dev
data:
  application.yaml: |-
    spring:
      profiles: dev

    bean:
      message: scheduled-message-dev
      signal: signal-dev