kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-demo-app-config-prod
data:
  application.yaml: |-
    bean:
      message: scheduled-message-prod
      signal: signal-prod

    value:
      message: this is value annotation prod