apiVersion: apps/v1
kind: Deployment
# to parameterize the values

metadata:
  labels:
    app: k8s-demo-app-test
  name: k8s-demo-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app-test
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-demo-app-test
    spec:
      containers:
      - image: k8s-demo-app:0.0.1-SNAPSHOT
        name: k8s-demo-app-test
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: test
        volumeMounts:
          - name: my-secrets
            mountPath: /etc/secrets
            readOnly: true
      volumes:
        - name: my-secrets
          secret:
            secretName: mysecrets-test
            optional: false
