apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-demo-app-mount
  name: k8s-demo-app-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app-mount
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-demo-app-mount
    spec:
      containers:
      - image: k8s-demo-app:0.0.1-SNAPSHOT
        name: k8s-demo-app-mount
        volumeMounts:
          - name: my-secrets
            mountPath: /etc/secrets
            readOnly: true
          - name: my-configmap
            mountPath: /etc/configs
            readOnly: true
      volumes:
        - name: my-secrets
          secret:
            secretName: mysecrets-mount
            optional: false
        - name: my-configmap
          configMap:
            name: k8s-demo-app-config-mount
            optional: false

