welcome:
  message: api-local


bean:
  message: scheduled-local
  signal: signal-local
  testpassword1: password1local
  testpassword2: password1local

value:
  message: this is value annotation local

management:
  endpoint:
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.springframework.cloud.bootstrap.config: TRACE
    org.springframework.cloud.kubernetes: TRACE