kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-demo-app-config-prod
data:
  application.yaml: |-
    spring:
      profiles: prod

    bean:
      message: scheduled-message-prod-changed
      signal: signal-prod-changed