apiVersion: apps/v1
kind: Deployment
# to parameterize the values

metadata:
  labels:
    app: {{app-name}}
  name: {{app-name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{app-name}}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{app-name}}
    spec:
      containers:
      - image: {{image-name}}:{{image-tag}}
        name: {{conatiner-name}}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: {{spring-active-profile}}
        volumeMounts:
          - name: {{secret-volume-name}}
            mountPath: {{mount-path}}
            readOnly: true
      volumes:
        - name: {{secret-volume-name}}
          secret:
            secretName: {{k8s-secret-obj}}
            optional: false
