kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-demo-app-config
data:
  application.yaml: |-
    welcome:
      message: api-configmap-base2-hehe

    bean:
      message: scheduled-configmap-base2-hehe
      signal: signal-base2-hehe