apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-demo-app
  name: k8s-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      containers:
      - image: k8s-demo-app:0.0.1-SNAPSHOT
        name: k8s-demo-app
        volumeMounts:
          - name: my-secrets
            mountPath: "/etc/secrets"
            readOnly: true
          - name: my-configmap
            mountPath: "/etc/configs"
            readOnly: true
      volumes:
        - name: my-secrets
          secret:
            secretName: mysecrets
            optional: false
        - name: my-configmap
          configMap:
            name: k8s-demo-app-config
            optional: false
#        envFrom:
#          - configMapRef:
#              name: literal-configmap

#        env:
#          - name: SPRING_PROFILES_ACTIVE
#            value: "test"
#        resources: {}
status: {}
