apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-demo-app
  name: k8s-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-demo-app
    spec:
      containers:
      - image: k8s-demo-app:0.0.1-SNAPSHOT
        name: k8s-demo-app
        envFrom:
          - configMapRef:
              name: literal-configmap
        resources: {}
status: {}
